name: test-env-xroms
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  # required
  - numpy
  - xarray
  - xgcm>=0.10
  - numba
  - dask
  # optional features exercised by the tests
  - gsw
  - pyproj
  - pooch
  # tests
  - netcdf4
  - pandas
  - pytest
  - pytest-cov
  - pip
